"""
SmartServe WaiterRequest Model

Tracks table assistance and call waiter requests generated by customers.
Allows real-time notification to Kitchen KDS and resolution tracking.
"""

from typing import Optional
from datetime import datetime, timezone
from sqlalchemy import Column, String, Text, DateTime
from sqlalchemy.orm import Mapped
import uuid

from app.database.base import BaseModel, UUID


class WaiterRequest(BaseModel):
    """
    Represents a Customer 'Call Waiter' or assistance request.
    """
    __tablename__ = "waiter_requests"

    table_number: Mapped[str] = Column(String(50), nullable=False, index=True)
    restaurant_id: Mapped[Optional[uuid.UUID]] = Column(
        UUID(as_uuid=True), nullable=True, index=True
    )
    request_type: Mapped[str] = Column(
        String(50), default="CALL_WAITER", nullable=False
    )
    status: Mapped[str] = Column(
        String(50), default="pending", nullable=False, index=True
    )  # "pending", "acknowledged", "resolved", "cancelled"
    notes: Mapped[Optional[str]] = Column(Text, nullable=True)
    resolved_at: Mapped[Optional[datetime]] = Column(
        DateTime(timezone=True), nullable=True
    )
    resolved_by: Mapped[Optional[str]] = Column(String(255), nullable=True)

    def to_dict(self) -> dict:
        return {
            "id": str(self.id),
            "table_number": str(self.table_number),
            "request_type": self.request_type,
            "status": self.status,
            "notes": self.notes or "",
            "created_at": self.created_at.isoformat() if self.created_at else None,
            "updated_at": self.updated_at.isoformat() if self.updated_at else None,
            "resolved_at": self.resolved_at.isoformat() if self.resolved_at else None,
            "resolved_by": self.resolved_by,
        }
