"""
SmartServe Menu Seed Data Script
Idempotent script to populate high-quality, realistic restaurant menu items and categories.
"""

import asyncio
import uuid
import re
from typing import List, Dict, Any
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.future import select

from app.database.connection import engine, async_session_factory
from app.database.base import Base
from app.models.restaurant import Restaurant
from app.models.category import Category
from app.models.menu import MenuItem
from app.core.logging import logger


def generate_slug(text: str) -> str:
    slug = text.lower().strip()
    slug = re.sub(r'[^\w\s-]', '', slug)
    slug = re.sub(r'[\s_-]+', '-', slug)
    return slug


SEED_CATEGORIES: List[Dict[str, Any]] = [
    {
        "name": "Starters",
        "description": "Appetizing starters and small bites to begin your meal",
        "icon": "Utensils",
        "display_order": 1,
        "items": [
            {
                "name": "Paneer Tikka",
                "description": "Cottage cheese cubes marinated in spiced yogurt and grilled to perfection in tandoor.",
                "price": 240.0,
                "compare_price": 280.0,
                "image_url": "https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?auto=format&fit=crop&w=800&q=80",
                "is_vegetarian": True,
                "is_todays_special": True,
                "is_featured": True,
                "is_spicy": True,
                "preparation_time": 15,
                "rating": 4.8,
                "rating_count": 142,
            },
            {
                "name": "Veg Manchurian",
                "description": "Crispy vegetable balls tossed in a tangy and spicy Indo-Chinese Manchurian sauce.",
                "price": 210.0,
                "compare_price": 240.0,
                "image_url": "https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=800&q=80",
                "is_vegetarian": True,
                "is_todays_special": False,
                "is_featured": True,
                "is_spicy": True,
                "preparation_time": 15,
                "rating": 4.6,
                "rating_count": 98,
            },
            {
                "name": "Hara Bhara Kebab",
                "description": "Pan-fried patties made of spinach, green peas, potatoes, and subtle aromatic spices.",
                "price": 190.0,
                "compare_price": 220.0,
                "image_url": "https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=800&q=80",
                "is_vegetarian": True,
                "is_todays_special": False,
                "is_featured": False,
                "is_spicy": False,
                "preparation_time": 12,
                "rating": 4.5,
                "rating_count": 76,
            },
            {
                "name": "Crispy Corn",
                "description": "Golden sweet corn kernels battered and fried crisp, tossed with herbs and chili lime.",
                "price": 180.0,
                "compare_price": 200.0,
                "image_url": "https://images.unsplash.com/photo-1551782450-a2132b4ba21d?auto=format&fit=crop&w=800&q=80",
                "is_vegetarian": True,
                "is_todays_special": False,
                "is_featured": True,
                "is_spicy": False,
                "preparation_time": 10,
                "rating": 4.7,
                "rating_count": 110,
            },
            {
                "name": "Chilli Paneer",
                "description": "Crispy paneer cubes tossed with capsicum, onion, and rich schezwan chili sauce.",
                "price": 230.0,
                "compare_price": 260.0,
                "image_url": "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=800&q=80",
                "is_vegetarian": True,
                "is_todays_special": False,
                "is_featured": True,
                "is_spicy": True,
                "preparation_time": 15,
                "rating": 4.6,
                "rating_count": 134,
            },
            {
                "name": "Veg Spring Rolls",
                "description": "Crispy thin wrappers stuffed with stir-fried cabbage, carrots, and glass noodles.",
                "price": 170.0,
                "compare_price": 195.0,
                "image_url": "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80",
                "is_vegetarian": True,
                "is_todays_special": False,
                "is_featured": False,
                "is_spicy": False,
                "preparation_time": 12,
                "rating": 4.4,
                "rating_count": 65,
            },
            {
                "name": "Chicken Tikka",
                "description": "Boneless chicken chunks marinated in spiced yogurt and roasted in a traditional clay oven.",
                "price": 280.0,
                "compare_price": 320.0,
                "image_url": "https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?auto=format&fit=crop&w=800&q=80",
                "is_vegetarian": False,
                "is_todays_special": True,
                "is_featured": True,
                "is_spicy": True,
                "preparation_time": 20,
                "rating": 4.9,
                "rating_count": 210,
            },
        ]
    },
    {
        "name": "North Indian",
        "description": "Authentic North Indian curries, rich gravies, and fresh tandoori breads",
        "icon": "Soup",
        "display_order": 2,
        "items": [
            {
                "name": "Paneer Butter Masala",
                "description": "Rich and creamy tomato gravy cooked with succulent paneer cubes, butter, and cashews.",
                "price": 280.0,
                "compare_price": 320.0,
                "image_url": "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=800&q=80",
                "is_vegetarian": True,
                "is_todays_special": True,
                "is_featured": True,
                "is_spicy": False,
                "preparation_time": 20,
                "rating": 4.9,
                "rating_count": 320,
            },
            {
                "name": "Kadai Paneer",
                "description": "Paneer cooked with bell peppers, onions, and freshly ground kadai masala spices.",
                "price": 270.0,
                "compare_price": 300.0,
                "image_url": "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&w=800&q=80",
                "is_vegetarian": True,
                "is_todays_special": False,
                "is_featured": True,
                "is_spicy": True,
                "preparation_time": 18,
                "rating": 4.7,
                "rating_count": 180,
            },
            {
                "name": "Dal Makhani",
                "description": "Black lentils slow-cooked overnight with cream, butter, and subtle aromatic spices.",
                "price": 230.0,
                "compare_price": 260.0,
                "image_url": "https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=800&q=80",
                "is_vegetarian": True,
                "is_todays_special": False,
                "is_featured": True,
                "is_spicy": False,
                "preparation_time": 25,
                "rating": 4.8,
                "rating_count": 250,
            },
            {
                "name": "Shahi Paneer",
                "description": "Royal Mughlai paneer curry cooked in a fragrant cashew-almond cream sauce.",
                "price": 290.0,
                "compare_price": 330.0,
                "image_url": "https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=800&q=80",
                "is_vegetarian": True,
                "is_todays_special": True,
                "is_featured": False,
                "is_spicy": False,
                "preparation_time": 20,
                "rating": 4.7,
                "rating_count": 115,
            },
            {
                "name": "Chole Bhature",
                "description": "Spicy chickpea curry served with two large fluffy deep-fried bhaturas and pickles.",
                "price": 180.0,
                "compare_price": 210.0,
                "image_url": "https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=800&q=80",
                "is_vegetarian": True,
                "is_todays_special": False,
                "is_featured": True,
                "is_spicy": True,
                "preparation_time": 15,
                "rating": 4.8,
                "rating_count": 290,
            },
            {
                "name": "Butter Naan",
                "description": "Leavened refined flour flatbread baked in tandoor and brushed generously with butter.",
                "price": 50.0,
                "compare_price": 60.0,
                "image_url": "https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=800&q=80",
                "is_vegetarian": True,
                "is_todays_special": False,
                "is_featured": False,
                "is_spicy": False,
                "preparation_time": 8,
                "rating": 4.6,
                "rating_count": 410,
            },
            {
                "name": "Garlic Naan",
                "description": "Tandoori naan infused with minced garlic and coriander, finished with butter.",
                "price": 60.0,
                "compare_price": 75.0,
                "image_url": "https://images.unsplash.com/photo-1610057099443-fde8c4d50f91?auto=format&fit=crop&w=800&q=80",
                "is_vegetarian": True,
                "is_todays_special": False,
                "is_featured": True,
                "is_spicy": False,
                "preparation_time": 8,
                "rating": 4.8,
                "rating_count": 380,
            },
            {
                "name": "Tandoori Roti",
                "description": "Whole wheat bread baked crisp in a traditional Indian clay oven.",
                "price": 30.0,
                "compare_price": 35.0,
                "image_url": "https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=800&q=80",
                "is_vegetarian": True,
                "is_todays_special": False,
                "is_featured": False,
                "is_spicy": False,
                "preparation_time": 5,
                "rating": 4.4,
                "rating_count": 210,
            },
        ]
    },
    {
        "name": "South Indian",
        "description": "Crispy dosas, soft idlis, and fragrant South Indian delicacies",
        "icon": "Flame",
        "display_order": 3,
        "items": [
            {
                "name": "Masala Dosa",
                "description": "Crispy rice and lentil crepe stuffed with spiced potato filling, served with coconut chutney & sambar.",
                "price": 140.0,
                "compare_price": 160.0,
                "image_url": "https://images.unsplash.com/photo-1668236543090-82eba5ee5976?auto=format&fit=crop&w=800&q=80",
                "is_vegetarian": True,
                "is_todays_special": True,
                "is_featured": True,
                "is_spicy": False,
                "preparation_time": 12,
                "rating": 4.9,
                "rating_count": 450,
            },
            {
                "name": "Plain Dosa",
                "description": "Golden crispy fermented crepe served with fresh coconut chutney and hot lentil sambar.",
                "price": 110.0,
                "compare_price": 130.0,
                "image_url": "https://images.unsplash.com/photo-1668236543090-82eba5ee5976?auto=format&fit=crop&w=800&q=80",
                "is_vegetarian": True,
                "is_todays_special": False,
                "is_featured": False,
                "is_spicy": False,
                "preparation_time": 10,
                "rating": 4.6,
                "rating_count": 190,
            },
            {
                "name": "Idli Sambar",
                "description": "Steamed fluffy rice cakes (3 pcs) served piping hot with vegetable sambar and red chutney.",
                "price": 90.0,
                "compare_price": 110.0,
                "image_url": "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=800&q=80",
                "is_vegetarian": True,
                "is_todays_special": False,
                "is_featured": True,
                "is_spicy": False,
                "preparation_time": 8,
                "rating": 4.7,
                "rating_count": 310,
            },
            {
                "name": "Medu Vada",
                "description": "Crispy fried lentil donuts (2 pcs) with soft interior, served with coconut chutney & sambar.",
                "price": 100.0,
                "compare_price": 120.0,
                "image_url": "https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=800&q=80",
                "is_vegetarian": True,
                "is_todays_special": False,
                "is_featured": False,
                "is_spicy": False,
                "preparation_time": 10,
                "rating": 4.5,
                "rating_count": 140,
            },
            {
                "name": "Onion Rava Dosa",
                "description": "Lacy and ultra-crispy semolina crepe topped with chopped onions, green chilies, and cumin.",
                "price": 160.0,
                "compare_price": 185.0,
                "image_url": "https://images.unsplash.com/photo-1668236543090-82eba5ee5976?auto=format&fit=crop&w=800&q=80",
                "is_vegetarian": True,
                "is_todays_special": True,
                "is_featured": True,
                "is_spicy": True,
                "preparation_time": 15,
                "rating": 4.8,
                "rating_count": 175,
            },
            {
                "name": "Masala Vada",
                "description": "Crunchy chana dal fritters tempered with curry leaves, onions, and fennel seeds.",
                "price": 95.0,
                "compare_price": 115.0,
                "image_url": "https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=800&q=80",
                "is_vegetarian": True,
                "is_todays_special": False,
                "is_featured": False,
                "is_spicy": True,
                "preparation_time": 10,
                "rating": 4.4,
                "rating_count": 85,
            },
        ]
    },
    {
        "name": "Chinese",
        "description": "Indo-Chinese noodles, fried rice, and wok-tossed favorites",
        "icon": "CookingPot",
        "display_order": 4,
        "items": [
            {
                "name": "Hakka Noodles",
                "description": "Wok-tossed noodles with crunchy bell peppers, cabbage, carrots, and soy sauce seasoning.",
                "price": 180.0,
                "compare_price": 210.0,
                "image_url": "https://images.unsplash.com/photo-1585032226651-759b368d7246?auto=format&fit=crop&w=800&q=80",
                "is_vegetarian": True,
                "is_todays_special": False,
                "is_featured": True,
                "is_spicy": False,
                "preparation_time": 12,
                "rating": 4.7,
                "rating_count": 280,
            },
            {
                "name": "Schezwan Fried Rice",
                "description": "Spicy fried rice tossed with fresh garden vegetables and in-house fiery schezwan sauce.",
                "price": 190.0,
                "compare_price": 220.0,
                "image_url": "https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=800&q=80",
                "is_vegetarian": True,
                "is_todays_special": False,
                "is_featured": True,
                "is_spicy": True,
                "preparation_time": 15,
                "rating": 4.6,
                "rating_count": 195,
            },
            {
                "name": "Veg Fried Rice",
                "description": "Aromatic long-grain rice stir-fried with finely chopped vegetables and mild Asian spices.",
                "price": 170.0,
                "compare_price": 195.0,
                "image_url": "https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=800&q=80",
                "is_vegetarian": True,
                "is_todays_special": False,
                "is_featured": False,
                "is_spicy": False,
                "preparation_time": 12,
                "rating": 4.5,
                "rating_count": 150,
            },
            {
                "name": "Chilli Mushroom",
                "description": "Batter-fried button mushrooms sautéed with bell peppers, garlic, and savory dark soy sauce.",
                "price": 210.0,
                "compare_price": 245.0,
                "image_url": "https://images.unsplash.com/photo-1541544741938-0af808871cc0?auto=format&fit=crop&w=800&q=80",
                "is_vegetarian": True,
                "is_todays_special": True,
                "is_featured": False,
                "is_spicy": True,
                "preparation_time": 15,
                "rating": 4.6,
                "rating_count": 92,
            },
            {
                "name": "Chicken Noodles",
                "description": "Stir-fried Hakka noodles with tender chicken strips, scrambled egg, and garden veggies.",
                "price": 220.0,
                "compare_price": 255.0,
                "image_url": "https://images.unsplash.com/photo-1612927601601-6638404737ce?auto=format&fit=crop&w=800&q=80",
                "is_vegetarian": False,
                "is_todays_special": False,
                "is_featured": True,
                "is_spicy": False,
                "preparation_time": 15,
                "rating": 4.8,
                "rating_count": 260,
            },
        ]
    },
    {
        "name": "Fast Food",
        "description": "Quick bites, fries, grilled sandwiches, and loaded wraps",
        "icon": "Sandwich",
        "display_order": 5,
        "items": [
            {
                "name": "French Fries",
                "description": "Golden salted potato fries, crispy on the outside and fluffy on the inside.",
                "price": 120.0,
                "compare_price": 140.0,
                "image_url": "https://images.unsplash.com/photo-1576107232684-1279f3908594?auto=format&fit=crop&w=800&q=80",
                "is_vegetarian": True,
                "is_todays_special": False,
                "is_featured": True,
                "is_spicy": False,
                "preparation_time": 8,
                "rating": 4.6,
                "rating_count": 340,
            },
            {
                "name": "Peri Peri Fries",
                "description": "Hot crispy fries dusted with zesty African peri peri spice blend.",
                "price": 140.0,
                "compare_price": 165.0,
                "image_url": "https://images.unsplash.com/photo-1585109649139-366815a0d713?auto=format&fit=crop&w=800&q=80",
                "is_vegetarian": True,
                "is_todays_special": True,
                "is_featured": True,
                "is_spicy": True,
                "preparation_time": 10,
                "rating": 4.8,
                "rating_count": 290,
            },
            {
                "name": "Veg Sandwich",
                "description": "Fresh bread slice layered with cucumbers, tomatoes, potatoes, mint chutney, and butter.",
                "price": 110.0,
                "compare_price": 130.0,
                "image_url": "https://images.unsplash.com/photo-1528735602780-2552fd46c7af?auto=format&fit=crop&w=800&q=80",
                "is_vegetarian": True,
                "is_todays_special": False,
                "is_featured": False,
                "is_spicy": False,
                "preparation_time": 10,
                "rating": 4.4,
                "rating_count": 120,
            },
            {
                "name": "Grilled Cheese Sandwich",
                "description": "Triple-decker bread loaded with melted cheddar, mozzarella, and green chutney, grilled crisp.",
                "price": 150.0,
                "compare_price": 180.0,
                "image_url": "https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=800&q=80",
                "is_vegetarian": True,
                "is_todays_special": False,
                "is_featured": True,
                "is_spicy": False,
                "preparation_time": 12,
                "rating": 4.7,
                "rating_count": 210,
            },
            {
                "name": "Cheese Garlic Bread",
                "description": "Toasted baguette slices topped with herb garlic butter and melted mozzarella cheese.",
                "price": 160.0,
                "compare_price": 190.0,
                "image_url": "https://images.unsplash.com/photo-1573140247632-f8fd74997d5c?auto=format&fit=crop&w=800&q=80",
                "is_vegetarian": True,
                "is_todays_special": False,
                "is_featured": True,
                "is_spicy": False,
                "preparation_time": 12,
                "rating": 4.8,
                "rating_count": 185,
            },
            {
                "name": "Veg Wrap",
                "description": "Whole wheat tortilla filled with crispy veggie patty, lettuce, mayonnaise, and chipotle sauce.",
                "price": 130.0,
                "compare_price": 155.0,
                "image_url": "https://images.unsplash.com/photo-1626700051175-6818013e1d4f?auto=format&fit=crop&w=800&q=80",
                "is_vegetarian": True,
                "is_todays_special": False,
                "is_featured": False,
                "is_spicy": False,
                "preparation_time": 10,
                "rating": 4.5,
                "rating_count": 140,
            },
        ]
    },
    {
        "name": "Biryani",
        "description": "Rich dum biryanis cooked with aromatic basmati rice and premium spices",
        "icon": "Bowl",
        "display_order": 6,
        "items": [
            {
                "name": "Veg Hyderabadi Biryani",
                "description": "Fragrant basmati rice layered with spiced garden vegetables, saffron, mint, and fried onions.",
                "price": 240.0,
                "compare_price": 280.0,
                "image_url": "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=800&q=80",
                "is_vegetarian": True,
                "is_todays_special": False,
                "is_featured": True,
                "is_spicy": True,
                "preparation_time": 25,
                "rating": 4.8,
                "rating_count": 310,
            },
            {
                "name": "Paneer Dum Biryani",
                "description": "Slow-cooked dum biryani featuring marinated cottage cheese cubes, kewra water, and whole spices.",
                "price": 270.0,
                "compare_price": 310.0,
                "image_url": "https://images.unsplash.com/photo-1633945274405-b6c8069047b0?auto=format&fit=crop&w=800&q=80",
                "is_vegetarian": True,
                "is_todays_special": True,
                "is_featured": True,
                "is_spicy": False,
                "preparation_time": 25,
                "rating": 4.7,
                "rating_count": 220,
            },
            {
                "name": "Chicken Dum Biryani",
                "description": "Authentic Hyderabadi chicken biryani cooked on slow dum with long-grain basmati and secret spices.",
                "price": 320.0,
                "compare_price": 370.0,
                "image_url": "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=800&q=80",
                "is_vegetarian": False,
                "is_todays_special": True,
                "is_featured": True,
                "is_spicy": True,
                "preparation_time": 30,
                "rating": 4.9,
                "rating_count": 580,
            },
            {
                "name": "Chicken Tikka Biryani",
                "description": "Smoky tandoori chicken tikka pieces layered with spicy biryani rice and rich gravy.",
                "price": 350.0,
                "compare_price": 400.0,
                "image_url": "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=800&q=80",
                "is_vegetarian": False,
                "is_todays_special": True,
                "is_featured": True,
                "is_spicy": True,
                "preparation_time": 30,
                "rating": 4.9,
                "rating_count": 420,
            },
            {
                "name": "Mutton Biryani",
                "description": "Tender bone-in mutton chunks slow-cooked in traditional clay pot dum biryani rice.",
                "price": 390.0,
                "compare_price": 440.0,
                "image_url": "https://images.unsplash.com/photo-1633945274405-b6c8069047b0?auto=format&fit=crop&w=800&q=80",
                "is_vegetarian": False,
                "is_todays_special": True,
                "is_featured": True,
                "is_spicy": True,
                "preparation_time": 35,
                "rating": 4.9,
                "rating_count": 390,
            },
            {
                "name": "Egg Biryani",
                "description": "Boiled eggs roasted with biryani masala and layered with aromatic basmati rice.",
                "price": 220.0,
                "compare_price": 250.0,
                "image_url": "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=800&q=80",
                "is_vegetarian": False,
                "is_todays_special": False,
                "is_featured": False,
                "is_spicy": True,
                "preparation_time": 20,
                "rating": 4.5,
                "rating_count": 130,
            },
        ]
    },
    {
        "name": "Pizza",
        "description": "Hand-tossed Italian pizzas with rich cheese and gourmet toppings",
        "icon": "Pizza",
        "display_order": 7,
        "items": [
            {
                "name": "Margherita Pizza",
                "description": "Classic Italian pizza base topped with san marzano tomato sauce, fresh mozzarella, and basil leaves.",
                "price": 260.0,
                "compare_price": 300.0,
                "image_url": "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&w=800&q=80",
                "is_vegetarian": True,
                "is_todays_special": False,
                "is_featured": True,
                "is_spicy": False,
                "preparation_time": 18,
                "rating": 4.8,
                "rating_count": 360,
            },
            {
                "name": "Farmhouse Pizza",
                "description": "Loaded with fresh capsicum, juicy tomatoes, grilled mushrooms, sweet corn, and double cheese.",
                "price": 340.0,
                "compare_price": 390.0,
                "image_url": "https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=800&q=80",
                "is_vegetarian": True,
                "is_todays_special": False,
                "is_featured": True,
                "is_spicy": False,
                "preparation_time": 20,
                "rating": 4.7,
                "rating_count": 280,
            },
            {
                "name": "Paneer Tikka Pizza",
                "description": "Fusion favorite topped with spiced paneer tikka, red onion, capsicum, and makhani drizzle.",
                "price": 380.0,
                "compare_price": 430.0,
                "image_url": "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&w=800&q=80",
                "is_vegetarian": True,
                "is_todays_special": True,
                "is_featured": True,
                "is_spicy": True,
                "preparation_time": 20,
                "rating": 4.9,
                "rating_count": 310,
            },
            {
                "name": "Veggie Supreme",
                "description": "Black olives, jalapenos, mushrooms, baby corn, onions, capsicum, and extra mozzarella.",
                "price": 360.0,
                "compare_price": 410.0,
                "image_url": "https://images.unsplash.com/photo-1571407970349-bc81e7e96d47?auto=format&fit=crop&w=800&q=80",
                "is_vegetarian": True,
                "is_todays_special": False,
                "is_featured": False,
                "is_spicy": True,
                "preparation_time": 20,
                "rating": 4.6,
                "rating_count": 190,
            },
            {
                "name": "Cheese Burst Pizza",
                "description": "Double crust stuffed with liquid cheddar cheese and topped with mozzarella and herbs.",
                "price": 420.0,
                "compare_price": 480.0,
                "image_url": "https://images.unsplash.com/photo-1593560708920-61dd98c46a4e?auto=format&fit=crop&w=800&q=80",
                "is_vegetarian": True,
                "is_todays_special": True,
                "is_featured": True,
                "is_spicy": False,
                "preparation_time": 22,
                "rating": 4.9,
                "rating_count": 410,
            },
            {
                "name": "Pepperoni Pizza",
                "description": "Hand-stretched pizza topped with tangy tomato sauce, mozzarella, and savory chicken pepperoni.",
                "price": 450.0,
                "compare_price": 500.0,
                "image_url": "https://images.unsplash.com/photo-1628840042765-356cda07504e?auto=format&fit=crop&w=800&q=80",
                "is_vegetarian": False,
                "is_todays_special": True,
                "is_featured": True,
                "is_spicy": False,
                "preparation_time": 20,
                "rating": 4.8,
                "rating_count": 270,
            },
        ]
    },
    {
        "name": "Burgers",
        "description": "Juicy artisan burgers with fresh buns and delicious fillings",
        "icon": "Ham",
        "display_order": 8,
        "items": [
            {
                "name": "Classic Veg Burger",
                "description": "Crispy vegetable patty with lettuce, tomato, onion, and mayonnaise on toasted sesame bun.",
                "price": 120.0,
                "compare_price": 145.0,
                "image_url": "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=800&q=80",
                "is_vegetarian": True,
                "is_todays_special": False,
                "is_featured": False,
                "is_spicy": False,
                "preparation_time": 10,
                "rating": 4.5,
                "rating_count": 180,
            },
            {
                "name": "Cheese Burst Veg Burger",
                "description": "Veggie patty stuffed with liquid cheese, topped with cheddar slice and house burger sauce.",
                "price": 160.0,
                "compare_price": 190.0,
                "image_url": "https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=800&q=80",
                "is_vegetarian": True,
                "is_todays_special": False,
                "is_featured": True,
                "is_spicy": False,
                "preparation_time": 12,
                "rating": 4.7,
                "rating_count": 240,
            },
            {
                "name": "Spicy Paneer Burger",
                "description": "Crispy fried cottage cheese patty marinated in hot peri peri spices with mint mayo.",
                "price": 190.0,
                "compare_price": 220.0,
                "image_url": "https://images.unsplash.com/photo-1571091718767-18b5b1457add?auto=format&fit=crop&w=800&q=80",
                "is_vegetarian": True,
                "is_todays_special": True,
                "is_featured": True,
                "is_spicy": True,
                "preparation_time": 15,
                "rating": 4.8,
                "rating_count": 210,
            },
            {
                "name": "Crispy Chicken Burger",
                "description": "Golden fried chicken breast fillet with crisp lettuce, pickles, and creamy garlic mayo.",
                "price": 220.0,
                "compare_price": 255.0,
                "image_url": "https://images.unsplash.com/photo-1615557960916-5f4791effe9d?auto=format&fit=crop&w=800&q=80",
                "is_vegetarian": False,
                "is_todays_special": True,
                "is_featured": True,
                "is_spicy": False,
                "preparation_time": 15,
                "rating": 4.9,
                "rating_count": 350,
            },
            {
                "name": "Double Cheese Burger",
                "description": "Double veggie patties layered with two cheddar cheese slices and caramelized onions.",
                "price": 210.0,
                "compare_price": 245.0,
                "image_url": "https://images.unsplash.com/photo-1586190848861-99aa4a171e90?auto=format&fit=crop&w=800&q=80",
                "is_vegetarian": True,
                "is_todays_special": False,
                "is_featured": False,
                "is_spicy": False,
                "preparation_time": 12,
                "rating": 4.6,
                "rating_count": 160,
            },
        ]
    },
    {
        "name": "Desserts",
        "description": "Indulgent sweets, cakes, Indian mithais, and cold desserts",
        "icon": "Cake",
        "display_order": 9,
        "items": [
            {
                "name": "Gulab Jamun",
                "description": "Soft fried milk solids dumplings (2 pcs) soaked in rose and cardamom scented sugar syrup.",
                "price": 90.0,
                "compare_price": 110.0,
                "image_url": "https://images.unsplash.com/photo-1605197586548-0ae906a2e212?auto=format&fit=crop&w=800&q=80",
                "is_vegetarian": True,
                "is_todays_special": False,
                "is_featured": True,
                "is_spicy": False,
                "preparation_time": 5,
                "rating": 4.9,
                "rating_count": 390,
            },
            {
                "name": "Rasmalai",
                "description": "Soft cottage cheese discs (2 pcs) chilled in pistachio and saffron infused reduced milk.",
                "price": 120.0,
                "compare_price": 145.0,
                "image_url": "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=800&q=80",
                "is_vegetarian": True,
                "is_todays_special": True,
                "is_featured": True,
                "is_spicy": False,
                "preparation_time": 5,
                "rating": 4.9,
                "rating_count": 340,
            },
            {
                "name": "Sizzling Brownie with Ice Cream",
                "description": "Warm chocolate fudgy brownie served on a sizzler plate topped with scoop of vanilla ice cream.",
                "price": 190.0,
                "compare_price": 220.0,
                "image_url": "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=800&q=80",
                "is_vegetarian": True,
                "is_todays_special": True,
                "is_featured": True,
                "is_spicy": False,
                "preparation_time": 10,
                "rating": 4.9,
                "rating_count": 480,
            },
            {
                "name": "Chocolate Lava Cake",
                "description": "Warm chocolate cake filled with rich molten chocolate center that flows upon first cut.",
                "price": 150.0,
                "compare_price": 180.0,
                "image_url": "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=800&q=80",
                "is_vegetarian": True,
                "is_todays_special": False,
                "is_featured": False,
                "is_spicy": False,
                "preparation_time": 8,
                "rating": 4.8,
                "rating_count": 270,
            },
            {
                "name": "Vanilla & Chocolate Ice Cream",
                "description": "Twin scoops of premium Madagascar vanilla and rich dark chocolate ice cream.",
                "price": 80.0,
                "compare_price": 100.0,
                "image_url": "https://images.unsplash.com/photo-1570197788417-0e82375c9371?auto=format&fit=crop&w=800&q=80",
                "is_vegetarian": True,
                "is_todays_special": False,
                "is_featured": False,
                "is_spicy": False,
                "preparation_time": 5,
                "rating": 4.6,
                "rating_count": 190,
            },
            {
                "name": "Gajar Ka Halwa",
                "description": "Traditional winter dessert made of slow-cooked red carrots, khoya, milk, ghee, and nuts.",
                "price": 130.0,
                "compare_price": 155.0,
                "image_url": "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=800&q=80",
                "is_vegetarian": True,
                "is_todays_special": True,
                "is_featured": False,
                "is_spicy": False,
                "preparation_time": 5,
                "rating": 4.8,
                "rating_count": 230,
            },
        ]
    },
    {
        "name": "Beverages",
        "description": "Refreshing teas, cold coffees, thick shakes, and mocktails",
        "icon": "Coffee",
        "display_order": 10,
        "items": [
            {
                "name": "Masala Chai",
                "description": "Brewed Indian milk tea spiced with fresh ginger, cardamom, cloves, and cinnamon.",
                "price": 40.0,
                "compare_price": 50.0,
                "image_url": "https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=800&q=80",
                "is_vegetarian": True,
                "is_todays_special": False,
                "is_featured": True,
                "is_spicy": False,
                "preparation_time": 5,
                "rating": 4.9,
                "rating_count": 520,
            },
            {
                "name": "Cold Coffee with Ice Cream",
                "description": "Blended espresso shot with chilled milk, sugar, topped with vanilla ice cream and chocolate drizzle.",
                "price": 120.0,
                "compare_price": 145.0,
                "image_url": "https://images.unsplash.com/photo-1517701604599-bb29b565090c?auto=format&fit=crop&w=800&q=80",
                "is_vegetarian": True,
                "is_todays_special": False,
                "is_featured": True,
                "is_spicy": False,
                "preparation_time": 8,
                "rating": 4.8,
                "rating_count": 410,
            },
            {
                "name": "Fresh Lime Soda",
                "description": "Sparkling soda with freshly squeezed lime juice, available in sweet, salted, or mixed flavor.",
                "price": 70.0,
                "compare_price": 85.0,
                "image_url": "https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=800&q=80",
                "is_vegetarian": True,
                "is_todays_special": False,
                "is_featured": False,
                "is_spicy": False,
                "preparation_time": 5,
                "rating": 4.6,
                "rating_count": 210,
            },
            {
                "name": "Mango Thick Shake",
                "description": "Rich Alphonso mango pulp blended with whole milk and vanilla ice cream.",
                "price": 140.0,
                "compare_price": 165.0,
                "image_url": "https://images.unsplash.com/photo-1553530666-ba11a7da3888?auto=format&fit=crop&w=800&q=80",
                "is_vegetarian": True,
                "is_todays_special": True,
                "is_featured": True,
                "is_spicy": False,
                "preparation_time": 8,
                "rating": 4.9,
                "rating_count": 310,
            },
            {
                "name": "Chocolate Milkshake",
                "description": "Creamy chocolate shake made with Belgian chocolate sauce, milk, and cocoa powder.",
                "price": 130.0,
                "compare_price": 155.0,
                "image_url": "https://images.unsplash.com/photo-1572490122747-3968b75cc699?auto=format&fit=crop&w=800&q=80",
                "is_vegetarian": True,
                "is_todays_special": False,
                "is_featured": False,
                "is_spicy": False,
                "preparation_time": 8,
                "rating": 4.7,
                "rating_count": 250,
            },
            {
                "name": "Soft Drink",
                "description": "Chilled 330ml beverage can (Choice of Cola, Lemonade, or Orange).",
                "price": 60.0,
                "compare_price": 70.0,
                "image_url": "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&w=800&q=80",
                "is_vegetarian": True,
                "is_todays_special": False,
                "is_featured": False,
                "is_spicy": False,
                "preparation_time": 2,
                "rating": 4.4,
                "rating_count": 140,
            },
            {
                "name": "Mineral Water",
                "description": "1 Litre packaged purified drinking water bottle.",
                "price": 30.0,
                "compare_price": 35.0,
                "image_url": "https://images.unsplash.com/photo-1548839140-29a749e1bc4e?auto=format&fit=crop&w=800&q=80",
                "is_vegetarian": True,
                "is_todays_special": False,
                "is_featured": False,
                "is_spicy": False,
                "preparation_time": 1,
                "rating": 4.5,
                "rating_count": 180,
            },
        ]
    }
]


async def seed_menu_data(db: AsyncSession) -> Dict[str, int]:
    """
    Idempotent database seeder for restaurant categories and menu items.
    Updates existing items or inserts missing ones.
    """
    logger.info("Starting SmartServe Menu Seeding...")

    # 1. Fetch or create default restaurant
    res_query = await db.execute(select(Restaurant))
    restaurant = res_query.scalars().first()

    if not restaurant:
        restaurant = Restaurant(
            name="SmartServe Gourmet",
            slug="smartserve-gourmet",
            description="Premium Multi-Cuisine Fine Dining & Smart Restaurant",
            email="info@smartserve.com",
            phone="+91 9876543210",
            address_line1="123 Food Street, Tech Park",
            city="Bengaluru",
            state="Karnataka",
            postal_code="560001",
            country="IN",
            currency="INR",
            tax_rate=0.05,
            service_charge_rate=0.02,
            is_active=True,
            is_open=True,
        )
        db.add(restaurant)
        await db.commit()
        await db.refresh(restaurant)
        logger.info(f"Created default restaurant: {restaurant.name} ({restaurant.id})")

    categories_count = 0
    items_count = 0

    for cat_data in SEED_CATEGORIES:
        cat_slug = generate_slug(cat_data["name"])

        # Fetch category by slug & restaurant
        cat_stmt = select(Category).where(
            Category.restaurant_id == restaurant.id,
            Category.slug == cat_slug
        )
        cat_res = await db.execute(cat_stmt)
        category = cat_res.scalars().first()

        if not category:
            category = Category(
                restaurant_id=restaurant.id,
                name=cat_data["name"],
                slug=cat_slug,
                description=cat_data["description"],
                icon=cat_data.get("icon"),
                display_order=cat_data.get("display_order", 0),
                is_active=True,
                show_on_menu=True,
            )
            db.add(category)
            await db.commit()
            await db.refresh(category)
            categories_count += 1
        else:
            category.name = cat_data["name"]
            category.description = cat_data["description"]
            category.icon = cat_data.get("icon")
            category.display_order = cat_data.get("display_order", 0)
            category.is_active = True
            category.show_on_menu = True

        for item_data in cat_data["items"]:
            item_slug = generate_slug(item_data["name"])

            item_stmt = select(MenuItem).where(
                MenuItem.restaurant_id == restaurant.id,
                MenuItem.slug == item_slug
            )
            item_res = await db.execute(item_stmt)
            menu_item = item_res.scalars().first()

            if not menu_item:
                menu_item = MenuItem(
                    restaurant_id=restaurant.id,
                    category_id=category.id,
                    name=item_data["name"],
                    slug=item_slug,
                    description=item_data["description"],
                    short_description=item_data["description"][:100],
                    price=item_data["price"],
                    compare_price=item_data.get("compare_price"),
                    image_url=item_data["image_url"],
                    is_available=True,
                    is_active=True,
                    is_vegetarian=item_data.get("is_vegetarian", False),
                    is_todays_special=item_data.get("is_todays_special", False),
                    is_featured=item_data.get("is_featured", False),
                    is_spicy=item_data.get("is_spicy", False),
                    preparation_time=item_data.get("preparation_time", 15),
                    rating=item_data.get("rating", 4.5),
                    rating_count=item_data.get("rating_count", 50),
                    stock_quantity=100,
                )
                db.add(menu_item)
                items_count += 1
            else:
                menu_item.category_id = category.id
                menu_item.name = item_data["name"]
                menu_item.description = item_data["description"]
                menu_item.price = item_data["price"]
                menu_item.compare_price = item_data.get("compare_price")
                menu_item.image_url = item_data["image_url"]
                menu_item.is_vegetarian = item_data.get("is_vegetarian", False)
                menu_item.is_todays_special = item_data.get("is_todays_special", False)
                menu_item.is_featured = item_data.get("is_featured", False)
                menu_item.is_spicy = item_data.get("is_spicy", False)
                menu_item.preparation_time = item_data.get("preparation_time", 15)
                menu_item.rating = item_data.get("rating", 4.5)
                menu_item.rating_count = item_data.get("rating_count", 50)
                menu_item.is_available = True
                menu_item.is_active = True

        await db.commit()

    logger.info(f"Menu Seeding complete. Processed {len(SEED_CATEGORIES)} categories and {sum(len(c['items']) for c in SEED_CATEGORIES)} menu items.")
    return {"categories": len(SEED_CATEGORIES), "items": sum(len(c['items']) for c in SEED_CATEGORIES)}


async def main():
    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.create_all)
    async with async_session_factory() as session:
        await seed_menu_data(session)

if __name__ == "__main__":
    asyncio.run(main())
